import { Document, Folder } from '../../types/document';
import backendResume from '../../assets/Mebuge Kamsiyochukwu Brendan Resume-backend.pdf';
import frontendResume from '../../assets/Mebuge Kamsiyochukwu Brendan Resume-frontend.pdf';
import fullstackResume from '../../assets/Mebuge Kamsiyochukwu Brendan Resume-fullstack.pdf';
import mobileResume from '../../assets/Mebuge Kamsiyochukwu Brendan Resume-mobile.pdf';

export const mockFolders: Folder[] = [
  { id: '1', name: 'Resumes', count: 4 },
  { id: '2', name: 'Cover Letters', count: 3 },
  { id: '3', name: 'Portfolios', count: 1 },
  { id: '4', name: 'Certificates', count: 2 },
  { id: '5', name: 'Work Samples', count: 5 },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    name: 'Brendan_Resume_Frontend.pdf',
    type: 'resume',
    format: 'pdf',
    size: 450 * 1024,
    uploadDate: '2026-05-20T10:30:00Z',
    modifiedDate: '2026-05-21T14:20:00Z',
    tags: ['Frontend', 'React', 'TypeScript', 'UI/UX'],
    folderId: '1',
    favorite: true,
    isPrimary: false,
    version: 'v3',
    url: frontendResume,
    description: 'Specialized in building pixel-perfect, high-performance UIs with React, TypeScript & Next.js. 3+ years crafting responsive interfaces, design systems, and seamless user experiences.',
  },
  {
    id: 'doc-2',
    name: 'Brendan_Resume_Backend.pdf',
    type: 'resume',
    format: 'pdf',
    size: 480 * 1024,
    uploadDate: '2026-05-18T09:15:00Z',
    modifiedDate: '2026-05-19T11:00:00Z',
    tags: ['Backend', 'Node.js', 'APIs', 'Databases'],
    folderId: '1',
    favorite: true,
    version: 'v2',
    url: backendResume,
    description: 'Expert in scalable server-side architectures with Node.js, Express & Python. Proficient in RESTful APIs, database design, authentication systems, and cloud deployment.',
  },
  {
    id: 'doc-3',
    name: 'Brendan_Resume_Fullstack.pdf',
    type: 'resume',
    format: 'pdf',
    size: 512 * 1024,
    uploadDate: '2026-05-15T09:15:00Z',
    modifiedDate: '2026-05-16T09:15:00Z',
    tags: ['Fullstack', 'React', 'Node.js', 'DevOps'],
    folderId: '1',
    favorite: true,
    isPrimary: true,
    version: 'v2',
    url: fullstackResume,
    description: 'End-to-end developer bridging frontend elegance with backend robustness. From database schemas to polished UIs — I deliver complete, production-ready solutions.',
  },
  {
    id: 'doc-4',
    name: 'Brendan_Resume_Mobile.pdf',
    type: 'resume',
    format: 'pdf',
    size: 440 * 1024,
    uploadDate: '2026-05-12T14:00:00Z',
    modifiedDate: '2026-05-13T10:30:00Z',
    tags: ['Mobile', 'React Native', 'Flutter', 'iOS/Android'],
    folderId: '1',
    favorite: true,
    version: 'v1',
    url: mobileResume,
    description: 'Building cross-platform mobile apps with React Native & Flutter. Experienced in native APIs, app store deployment, push notifications, and offline-first architectures.',
  },
  {
    id: 'doc-5',
    name: 'Google_Cover_Letter.docx',
    type: 'cover_letter',
    format: 'docx',
    size: 24 * 1024,
    uploadDate: '2026-05-24T16:45:00Z',
    modifiedDate: '2026-05-24T17:00:00Z',
    tags: ['Google', 'Software Engineer'],
    folderId: '2',
    favorite: true,
  },
  {
    id: 'doc-6',
    name: 'AWS_Certified_Developer.png',
    type: 'certificate',
    format: 'png',
    size: 1024 * 1024 * 2.1,
    uploadDate: '2025-11-15T08:00:00Z',
    modifiedDate: '2025-11-15T08:00:00Z',
    tags: ['AWS', 'Certification'],
    folderId: '4',
    favorite: false,
  },
  {
    id: 'doc-7',
    name: 'Portfolio_2026_Tech.pptx',
    type: 'portfolio',
    format: 'pptx',
    size: 1024 * 1024 * 5.4,
    uploadDate: '2026-01-10T11:20:00Z',
    modifiedDate: '2026-02-05T09:10:00Z',
    tags: ['Frontend', 'Design'],
    folderId: '3',
    favorite: true,
  }
];

export const mockStats = {
  totalFiles: 17,
  totalStorageUsed: 1024 * 1024 * 16.2,
  maxStorage: 1024 * 1024 * 1024 * 10,
  resumes: 4,
  coverLetters: 3,
  portfolios: 1,
};
